### PR TITLE
Uranium ore processing and enrichment, and fuel rod products

### PR DESCRIPTION
**Pull request by funions123**
-Uraninite ore processing and enrichment chain
-werkstoff materials support for gregtech crafting items and fluids
-gregtech recipe support
-fuel rod product class

### CODE REVIEW

**Comment by RecursivePineapple** [comment]
Other than the findItemStack calls, this looks good. Will you add the textures in a second PR, or will you ask a texture dev to make them?

**Comment by funions123** [comment]
I'll probably just make my own knockoff textures in a cleanup pass. That and the couple of missing langs.

**Comment by funions123** [comment]
closed for cleanup and merge into a bigger pr

**Comment by RecursivePineapple** [comment]
I don't care if PRs hang around for a while. If you want to draft it, I'm fine it.

**Pull request closed without merging**
